### ISSUE TITLE
Looking for a group of words

### ISSUE THREAD

**Issue by bouda1** [duane9/nvim-rg#3]
Hi,

In neo vim, if I enter `:Rg` and put for pattern something like `foo bar`, I'll get the files containing `foo bar`.

My issue, but maybe I do the wrong syntax, is when I enter `:Rg "foo bar"` then I can see at the bottom of neo vim a message `Searching...` that will never disappear. And I get no result.

Is this an issue, or should I use another syntax?
Thanks.

**Comment by duane9** [comment]
This has been fixed. `:Rg "foo bar"` now uses the default directory as expected. Thanks!
